### ISSUE TITLE
"error: shared_ptr is not a member of std" when build with g++ on ubuntu 16.04

### ISSUE THREAD

**Issue by daretobe** [olmallet81/URT#4]
I find out that shared_ptr is defined in <memory> under my environment:
- os:ubuntu16.04.4 4.13.0-31-generic
- compiler: gcc 5.4.0, default configuration

So I add 

> #include \<memory\>

in the file include/URT.hpp. The problem is solved.

**Comment by kangseung** [comment]
I have same error too. thanks your solve solution
